apiVersion: v1
kind: Service
metadata:
  name: fsc-products
  namespace: b-namespace
  labels: 
    app: fsc-products
    commit: ${GIT_COMMIT}
  annotations:
    service.beta.kubernetes.io/oci-load-balancer-internal: "true"

spec:
  type: LoadBalancer
  ports:
  - port: 8080
    targetPort: 8080
    protocol: TCP
  selector:
    app: fsc-products
