apiVersion: v1
kind: Service
metadata:
  name: fsc-products
  annotations:
    service.beta.kubernetes.io/oci-load-balancer-internal: "true"
spec:
  type: LoadBalancer
  ports:
  - port: 8888
    targetPort: 8080
    protocol: TCP
  selector:
    app: fsc-products