apiVersion: v1
kind: Service
metadata:
  name: fsc-products
  labels: 
    app: fsc-products
    commit: ${GIT_COMMIT}
spec:
  type: LoadBalancer
  ports:
  - port: 8080
    targetPort: 8080
    protocol: TCP
  selector:
    app: fsc-products
